import { createTable, addColumns } from '@nozbe/watermelondb/Schema/migrations';

const migration001 = {
  toVersion: 1,
  steps: [
    createTable({
      name: 'users',
      columns: [
        { name: 'email', type: 'string' },
        { name: 'display_name', type: 'string' },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'unit_preference', type: 'string' },
        { name: 'theme_preference', type: 'string' },
        { name: 'accent_colour', type: 'string' },
        { name: 'default_rest_seconds', type: 'number' },
        { name: 'one_rm_formula', type: 'string' },
        { name: 'training_goal', type: 'string' },
        { name: 'experience_level', type: 'string' },
        { name: 'date_of_birth', type: 'string', isOptional: true },
        { name: 'subscription_tier', type: 'string' },
        { name: 'subscription_expires_at', type: 'string', isOptional: true },
        { name: 'apple_health_linked', type: 'boolean' },
        { name: 'is_local_only', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'exercises',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'aliases', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'primary_muscles', type: 'string' },
        { name: 'secondary_muscles', type: 'string' },
        { name: 'equipment', type: 'string' },
        { name: 'movement_pattern', type: 'string' },
        { name: 'is_compound', type: 'boolean' },
        { name: 'is_unilateral', type: 'boolean' },
        { name: 'instructions', type: 'string' },
        { name: 'video_url', type: 'string', isOptional: true },
        { name: 'thumbnail_url', type: 'string', isOptional: true },
        { name: 'is_custom', type: 'boolean' },
        { name: 'created_by_user_id', type: 'string', isOptional: true },
        { name: 'is_archived', type: 'boolean' },
        { name: 'default_rest_seconds', type: 'number', isOptional: true },
        { name: 'default_rpe_target', type: 'number', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'workout_templates',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'program_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'estimated_duration_minutes', type: 'number', isOptional: true },
        { name: 'target_muscle_groups', type: 'string' },
        { name: 'is_built_in', type: 'boolean' },
        { name: 'is_archived', type: 'boolean' },
        { name: 'usage_count', type: 'number' },
        { name: 'last_used_at', type: 'number', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'template_exercises',
      columns: [
        { name: 'template_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'order_index', type: 'number' },
        { name: 'superset_group_id', type: 'string', isOptional: true },
        { name: 'rest_seconds', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'template_sets',
      columns: [
        { name: 'template_exercise_id', type: 'string', isIndexed: true },
        { name: 'order_index', type: 'number' },
        { name: 'set_type', type: 'string' },
        { name: 'target_reps', type: 'number', isOptional: true },
        { name: 'target_reps_max', type: 'number', isOptional: true },
        { name: 'target_weight', type: 'number', isOptional: true },
        { name: 'target_weight_modifier', type: 'string' },
        { name: 'target_rpe', type: 'number', isOptional: true },
        { name: 'is_amrap', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'programs',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'author', type: 'string', isOptional: true },
        { name: 'duration_weeks', type: 'number' },
        { name: 'days_per_week', type: 'number' },
        { name: 'target_goal', type: 'string' },
        { name: 'experience_level', type: 'string' },
        { name: 'is_built_in', type: 'boolean' },
        { name: 'deload_week', type: 'number', isOptional: true },
        { name: 'progression_rules', type: 'string' },
        { name: 'tags', type: 'string' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'program_slots',
      columns: [
        { name: 'program_id', type: 'string', isIndexed: true },
        { name: 'template_id', type: 'string', isIndexed: true },
        { name: 'week_number', type: 'number' },
        { name: 'day_number', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'workout_sessions',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'template_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'program_id', type: 'string', isOptional: true },
        { name: 'program_week', type: 'number', isOptional: true },
        { name: 'program_day', type: 'number', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'started_at', type: 'number' },
        { name: 'ended_at', type: 'number', isOptional: true },
        { name: 'duration_seconds', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'bodyweight_kg', type: 'number', isOptional: true },
        { name: 'preworkout_mood', type: 'string', isOptional: true },
        { name: 'mood', type: 'string', isOptional: true },
        { name: 'perceived_exertion', type: 'number', isOptional: true },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'total_volume_kg', type: 'number', isOptional: true },
        { name: 'total_sets', type: 'number', isOptional: true },
        { name: 'total_reps', type: 'number', isOptional: true },
        { name: 'is_deleted', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'session_exercises',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'session_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'order_index', type: 'number' },
        { name: 'superset_group_id', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'rest_seconds', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'sets',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'session_exercise_id', type: 'string', isIndexed: true },
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'set_number', type: 'number' },
        { name: 'set_type', type: 'string' },
        { name: 'weight_kg', type: 'number', isOptional: true },
        { name: 'weight_kg_actual', type: 'number', isOptional: true },
        { name: 'reps', type: 'number', isOptional: true },
        { name: 'rpe', type: 'number', isOptional: true },
        { name: 'rir', type: 'number', isOptional: true },
        { name: 'duration', type: 'number', isOptional: true },
        { name: 'distance', type: 'number', isOptional: true },
        { name: 'is_amrap', type: 'boolean' },
        { name: 'is_warmup', type: 'boolean' },
        { name: 'is_personal_record', type: 'boolean' },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'personal_records',
      columns: [
        { name: 'exercise_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'set_id', type: 'string' },
        { name: 'session_id', type: 'string', isIndexed: true },
        { name: 'record_type', type: 'string' },
        { name: 'value', type: 'number' },
        { name: 'previous_value', type: 'number', isOptional: true },
        { name: 'is_current_record', type: 'boolean' },
        { name: 'achieved_at', type: 'number' },
        { name: 'formula', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'body_measurements',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'measured_at', type: 'number' },
        { name: 'weight_kg', type: 'number', isOptional: true },
        { name: 'body_fat_percent', type: 'number', isOptional: true },
        { name: 'lean_mass_kg', type: 'number', isOptional: true },
        { name: 'measurements', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'photo_front_url', type: 'string', isOptional: true },
        { name: 'photo_side_url', type: 'string', isOptional: true },
        { name: 'photo_back_url', type: 'string', isOptional: true },
        { name: 'source', type: 'string' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'nutrition_logs',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true, },
        { name: 'log_date', type: 'string', isIndexed: true },
        { name: 'calories_kcal', type: 'number', isOptional: true },
        { name: 'protein_g', type: 'number', isOptional: true },
        { name: 'carbs_g', type: 'number', isOptional: true },
        { name: 'fat_g', type: 'number', isOptional: true },
        { name: 'fiber_g', type: 'number', isOptional: true },
        { name: 'water_ml', type: 'number', isOptional: true },
        { name: 'source', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'superset_groups',
      columns: [
        { name: 'session_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'template_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'group_type', type: 'string' },
        { name: 'max_size', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    createTable({
      name: 'sync_metadata',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'table_name', type: 'string' },
        { name: 'last_pulled_at', type: 'number', isOptional: true },
        { name: 'last_pushed_at', type: 'number', isOptional: true },
        { name: 'pending_changes', type: 'number' },
        { name: 'conflict_count', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
};

export default migration001;
