import type { ExerciseCategory, MuscleGroup, Equipment, MovementPattern } from '../types/enums';

interface BuiltInExercise {
  id: string;
  name: string;
  aliases: string[];
  category: ExerciseCategory;
  primaryMuscles: MuscleGroup[];
  secondaryMuscles: MuscleGroup[];
  equipment: Equipment[];
  movementPattern: MovementPattern;
  isCompound: boolean;
  isUnilateral: boolean;
  instructions: string;
  isCustom: false;
  isArchived: false;
  defaultRestSeconds: number | null;
}

export const BUILT_IN_EXERCISES: readonly BuiltInExercise[] = [
  // ─── BARBELL (30) ────────────────────────────────────────────────────────────

  {
    id: 'ex_barbell_back_squat',
    name: 'Back Squat',
    aliases: ['Barbell Squat', 'High Bar Squat', 'Low Bar Squat'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Position the barbell across your upper traps. Stand with feet shoulder-width apart and toes slightly out. Brace your core, break at hips and knees simultaneously, and descend until thighs are parallel to the floor or below. Drive through your heels to return to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_front_squat',
    name: 'Front Squat',
    aliases: ['Barbell Front Squat'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upper_back', 'lower_back'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Rest the barbell on your front delts with elbows high. Stand with feet shoulder-width apart. Keeping a tall torso, squat down until thighs are parallel or below, then drive up through your heels.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_conventional_deadlift',
    name: 'Conventional Deadlift',
    aliases: ['Deadlift', 'Barbell Deadlift'],
    category: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes', 'lower_back'],
    secondaryMuscles: ['quads', 'traps', 'lats', 'forearms'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with feet hip-width apart, bar over mid-foot. Hinge at hips and grip the bar just outside your legs. Brace your core, pull your chest up, then drive your feet into the floor while pulling the bar up your shins until lockout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_romanian_deadlift',
    name: 'Romanian Deadlift',
    aliases: ['RDL', 'Barbell RDL'],
    category: 'barbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'forearms'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold the bar at hip level with a shoulder-width grip. Keeping a slight knee bend and neutral spine, hinge at the hips and lower the bar along your legs until you feel a deep hamstring stretch. Drive your hips forward to return to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_hip_thrust',
    name: 'Hip Thrust',
    aliases: ['Barbell Hip Thrust', 'Glute Bridge Barbell'],
    category: 'barbell',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings', 'quads', 'abs'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit on the floor with your upper back against a bench and a padded barbell across your hips. Plant feet flat, hip-width apart. Drive through your heels to thrust your hips up until your body forms a straight line from knees to shoulders. Squeeze your glutes at the top.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_bench_press',
    name: 'Barbell Bench Press',
    aliases: ['Bench Press', 'Flat Bench'],
    category: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delt', 'shoulders'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench, grip the bar slightly wider than shoulder-width. Unrack, lower the bar with control to your mid-chest, then press back up explosively to lockout. Maintain a slight arch and keep your feet flat on the floor.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_incline_bench_press',
    name: 'Incline Bench Press',
    aliases: ['Incline Barbell Press'],
    category: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt', 'triceps'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set the bench to 30–45 degrees. Grip slightly wider than shoulder-width, unrack, and lower the bar to your upper chest. Press back up to lockout. Keep your feet flat and shoulder blades retracted throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_decline_bench_press',
    name: 'Decline Bench Press',
    aliases: ['Decline Barbell Press'],
    category: 'barbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delt'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set the bench to a 15–30 degree decline. Secure your legs and grip the bar slightly wider than shoulder-width. Lower to the lower chest and press back up to lockout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_overhead_press',
    name: 'Overhead Press',
    aliases: ['OHP', 'Military Press', 'Standing Press', 'Barbell Overhead Press'],
    category: 'barbell',
    primaryMuscles: ['shoulders', 'front_delt'],
    secondaryMuscles: ['triceps', 'traps', 'abs'],
    equipment: ['barbell'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with feet shoulder-width apart, bar resting on your front delts with a grip just outside shoulder-width. Brace your core and press the bar overhead to full lockout, moving your head back slightly to clear the bar path. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_row',
    name: 'Barbell Row',
    aliases: ['Bent-Over Row', 'Barbell Bent-Over Row'],
    category: 'barbell',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt', 'lower_back'],
    equipment: ['barbell'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hinge forward to about 45 degrees with a neutral spine, holding the bar with an overhand grip. Pull the bar to your lower sternum, driving your elbows back. Lower under control. Keep your torso angle consistent throughout the set.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_pendlay_row',
    name: 'Pendlay Row',
    aliases: ['Strict Barbell Row'],
    category: 'barbell',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['barbell'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set up with the bar on the floor. Hinge to a near-horizontal torso and pull the bar explosively to your lower chest from a dead stop each rep. Lower it all the way back to the floor between reps. Back stays parallel to the ground throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_curl',
    name: 'Barbell Curl',
    aliases: ['Standing Barbell Curl'],
    category: 'barbell',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand with feet shoulder-width apart, holding the bar with a supinated grip shoulder-width apart. Curl the bar to your upper chest, keeping your elbows tucked at your sides. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_barbell_close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    aliases: ['CGBP', 'Close Grip Bench'],
    category: 'barbell',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delt'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench and grip the bar with hands about shoulder-width apart. Lower to your lower chest, keeping your elbows tucked close to your torso, then press to lockout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_skullcrusher',
    name: 'Skullcrusher',
    aliases: ['Lying Tricep Extension', 'French Press', 'EZ Bar Skullcrusher'],
    category: 'barbell',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['barbell', 'bench', 'ez_bar'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench holding the bar above your forehead with a narrow overhand grip. Keeping your upper arms vertical and fixed, bend your elbows to lower the bar toward your forehead, then extend back to the top.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_barbell_good_morning',
    name: 'Good Morning',
    aliases: ['Barbell Good Morning'],
    category: 'barbell',
    primaryMuscles: ['hamstrings', 'lower_back'],
    secondaryMuscles: ['glutes'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Place the bar on your upper traps with feet shoulder-width apart. Keeping a slight knee bend and neutral spine, hinge at the hips and lower your torso until nearly parallel to the floor. Drive your hips forward to return to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_hack_squat',
    name: 'Barbell Hack Squat',
    aliases: ['Hack Squat Barbell'],
    category: 'barbell',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'hamstrings'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold the bar behind your legs at arm\'s length, palms facing back. Squat down by bending your knees while keeping your torso upright. Drive through your heels to stand, keeping the bar close to your legs.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_zercher_squat',
    name: 'Zercher Squat',
    aliases: ['Barbell Zercher Squat'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['abs', 'upper_back', 'biceps'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold the bar in the crook of your elbows at hip height. Stand with feet shoulder-width apart, toes out. Squat down keeping a tall, upright torso until your elbows touch the inside of your thighs. Drive back up to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_sumo_deadlift',
    name: 'Sumo Deadlift',
    aliases: ['Wide Stance Deadlift'],
    category: 'barbell',
    primaryMuscles: ['glutes', 'quads', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'traps', 'forearms'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with feet wider than shoulder-width with toes flared 30–60 degrees. Grip the bar inside your legs at shoulder-width. Drop your hips, brace, and drive the floor away while pushing your knees out. Lock out hips and knees simultaneously.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_pause_squat',
    name: 'Pause Squat',
    aliases: ['Barbell Pause Squat'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back', 'abs'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Perform a back squat and pause for 2–3 seconds in the bottom position, maintaining full tension. Drive out of the hole without bouncing. Use lighter load than your regular squat.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_box_squat',
    name: 'Box Squat',
    aliases: ['Barbell Box Squat'],
    category: 'barbell',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'lower_back'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set a box or bench to parallel or below. Perform a back squat and sit back onto the box, releasing hip flexor tension briefly, then drive explosively back to standing. Do not rock or use momentum.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_low_bar_squat',
    name: 'Low Bar Squat',
    aliases: ['Powerlifting Squat', 'LBS'],
    category: 'barbell',
    primaryMuscles: ['glutes', 'quads', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'abs'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Position the bar on your rear deltoids, below the spine of the scapula. Use a wider stance with more forward lean than a high-bar squat. Sit back and down, keeping your shins relatively vertical, then drive your hips forward to lockout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_snatch_grip_deadlift',
    name: 'Snatch-Grip Deadlift',
    aliases: ['Wide Grip Deadlift'],
    category: 'barbell',
    primaryMuscles: ['hamstrings', 'lower_back', 'glutes'],
    secondaryMuscles: ['traps', 'upper_back', 'forearms'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Use a very wide snatch-width grip (outside shoulder-width) with conventional deadlift stance. The wider grip forces a lower hip position and greater range of motion. Pull the same as a conventional deadlift but focus on upper back engagement.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_rack_pull',
    name: 'Rack Pull',
    aliases: ['Partial Deadlift', 'Rack Deadlift'],
    category: 'barbell',
    primaryMuscles: ['lower_back', 'traps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'forearms', 'upper_back'],
    equipment: ['barbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set safety pins to just below or at knee height. Pull the bar to lockout from this elevated position. Allows heavier loads than a full deadlift. Focus on driving your hips forward at the top and squeezing your glutes.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 180,
  },
  {
    id: 'ex_barbell_floor_press',
    name: 'Floor Press',
    aliases: ['Barbell Floor Press'],
    category: 'barbell',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['front_delt'],
    equipment: ['barbell'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Lie on the floor with the bar on J-hooks or handed off by a spotter. Lower the bar until your upper arms rest on the floor, pause briefly, then press back to lockout. The floor limits range of motion and removes leg drive.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 150,
  },
  {
    id: 'ex_barbell_lunge',
    name: 'Barbell Lunge',
    aliases: ['Walking Lunge Barbell', 'Barbell Reverse Lunge'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['barbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Hold the bar across your upper traps. Step forward and lower your back knee toward the floor, keeping your front shin vertical. Drive through your front heel to return to the start. Alternate legs or complete all reps on one side.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_bulgarian_split_squat',
    name: 'Barbell Bulgarian Split Squat',
    aliases: ['Bulgarian Split Squat Barbell', 'RFESS Barbell'],
    category: 'barbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell', 'bench'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Place the bar on your back and rest your rear foot on a bench behind you. Lower your hips down and forward until your front thigh is parallel to the floor. Drive through the front heel to return to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_barbell_shrug',
    name: 'Barbell Shrug',
    aliases: ['Barbell Trap Shrug'],
    category: 'barbell',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand holding the bar in front of your thighs with a double overhand grip. Shrug your shoulders straight up as high as possible, hold for a count, then lower under control. Do not roll your shoulders.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_barbell_upright_row',
    name: 'Upright Row',
    aliases: ['Barbell Upright Row'],
    category: 'barbell',
    primaryMuscles: ['traps', 'shoulders'],
    secondaryMuscles: ['front_delt', 'biceps'],
    equipment: ['barbell'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold the bar in front of your thighs with a shoulder-width or slightly narrower grip. Pull the bar straight up your body, leading with your elbows, until the bar reaches chin height. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_barbell_reverse_curl',
    name: 'Barbell Reverse Curl',
    aliases: ['Reverse Barbell Curl'],
    category: 'barbell',
    primaryMuscles: ['forearms', 'biceps'],
    secondaryMuscles: [],
    equipment: ['barbell', 'ez_bar'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Hold the bar with a pronated (overhand) grip at shoulder-width. Keeping elbows tucked at your sides, curl the bar to your upper chest. Lower under control. Focus on the brachioradialis.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_barbell_wrist_curl',
    name: 'Barbell Wrist Curl',
    aliases: ['Seated Wrist Curl Barbell'],
    category: 'barbell',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['barbell', 'bench'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Sit on a bench and rest your forearms on your thighs with your wrists hanging off the edge, palms facing up. Allow the bar to roll to your fingertips, then curl your wrists up as high as possible. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },

  // ─── DUMBBELL (20) ────────────────────────────────────────────────────────────

  {
    id: 'ex_db_bench_press',
    name: 'Dumbbell Bench Press',
    aliases: ['DB Bench Press', 'Flat DB Press'],
    category: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delt'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench with a dumbbell in each hand at chest level. Press both dumbbells up until your arms are fully extended, then lower with control to chest level.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_db_incline_press',
    name: 'Incline Dumbbell Press',
    aliases: ['Incline DB Press'],
    category: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt', 'triceps'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set the bench to 30–45 degrees. Press the dumbbells from chest level to full lockout. Lower under control to the starting position.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_db_row',
    name: 'Dumbbell Row',
    aliases: ['DB Row', 'One-Arm Row', 'Single Arm Dumbbell Row'],
    category: 'dumbbell',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Place one hand and knee on a bench for support. Holding a dumbbell in the opposite hand, row it to your hip by driving your elbow back past your torso. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_curl',
    name: 'Dumbbell Curl',
    aliases: ['DB Curl', 'Alternating Dumbbell Curl', 'Standing DB Curl'],
    category: 'dumbbell',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Stand holding dumbbells at your sides with palms facing forward. Curl both or alternating arms to your upper chest, keeping your elbows fixed at your sides. Supinate at the top for full bicep contraction.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_hammer_curl',
    name: 'Dumbbell Hammer Curl',
    aliases: ['DB Hammer Curl', 'Hammer Curl'],
    category: 'dumbbell',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Hold dumbbells at your sides with a neutral (palms facing inward) grip. Curl both or alternating arms up while maintaining the neutral grip throughout. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['DB Lateral Raise', 'Side Lateral Raise'],
    category: 'dumbbell',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand with dumbbells at your sides, slight bend in the elbows. Raise both arms out to the sides until parallel to the floor, leading with your elbows. Lower under control. Slightly tilt the front of the dumbbell down at the top.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_front_raise',
    name: 'Dumbbell Front Raise',
    aliases: ['DB Front Raise'],
    category: 'dumbbell',
    primaryMuscles: ['front_delt'],
    secondaryMuscles: ['shoulders'],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand with dumbbells in front of your thighs. Raise one or both arms straight in front of you to shoulder height. Lower under control. Maintain a slight bend in the elbows throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_rear_delt_fly',
    name: 'Dumbbell Rear Delt Fly',
    aliases: ['DB Reverse Fly', 'Bent-Over Rear Delt Raise', 'DB Rear Delt Raise'],
    category: 'dumbbell',
    primaryMuscles: ['rear_delt'],
    secondaryMuscles: ['upper_back', 'traps'],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Hinge forward until your torso is nearly parallel to the floor. Let the dumbbells hang below your chest. Raise both arms out to the sides, squeezing your rear delts at the top. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    aliases: ['DB Shoulder Press', 'DB Overhead Press', 'Arnold Press'],
    category: 'dumbbell',
    primaryMuscles: ['shoulders', 'front_delt'],
    secondaryMuscles: ['triceps', 'traps'],
    equipment: ['dumbbell'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit or stand with dumbbells at shoulder height, palms facing forward. Press both dumbbells overhead until your arms are extended. Lower under control back to shoulder height.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_db_goblet_squat',
    name: 'Dumbbell Goblet Squat',
    aliases: ['DB Goblet Squat', 'Goblet Squat'],
    category: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs'],
    equipment: ['dumbbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold a dumbbell vertically at chest height with both hands cupped around one end. Stand with feet shoulder-width apart and squat down, keeping elbows inside your knees at the bottom. Drive back up through your heels.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['DB RDL', 'Dumbbell RDL'],
    category: 'dumbbell',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower_back', 'forearms'],
    equipment: ['dumbbell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold dumbbells in front of your thighs with a neutral grip. With a slight knee bend, hinge at the hips and lower the dumbbells along your legs until you feel a deep hamstring stretch. Drive your hips forward to return.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_lunge',
    name: 'Dumbbell Lunge',
    aliases: ['DB Lunge', 'Walking Lunge Dumbbell'],
    category: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['dumbbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Hold dumbbells at your sides. Step forward and lower your back knee toward the floor, keeping your front shin vertical. Drive through your front heel to return. Alternate legs for walking lunges or step back for reverse lunges.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_step_up',
    name: 'Dumbbell Step-Up',
    aliases: ['DB Step-Up', 'Step-Up'],
    category: 'dumbbell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['dumbbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Hold dumbbells at your sides and face a bench or box. Step up with one foot, drive through the heel to stand on the box, then step down with control. Complete all reps on one side or alternate.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_chest_fly',
    name: 'Dumbbell Chest Fly',
    aliases: ['DB Fly', 'Dumbbell Pec Fly'],
    category: 'dumbbell',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench with dumbbells pressed together above your chest, palms facing each other. With a slight elbow bend, open your arms out in an arc until you feel a stretch across your chest. Bring the dumbbells back together at the top.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_skull_crusher',
    name: 'Dumbbell Skull Crusher',
    aliases: ['DB Skullcrusher', 'Lying DB Tricep Extension'],
    category: 'dumbbell',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Lie on a flat bench with dumbbells held above your chest, palms facing each other. Keeping upper arms vertical, bend your elbows to lower the dumbbells to the sides of your head. Extend back to the top.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_pullover',
    name: 'Dumbbell Pullover',
    aliases: ['DB Pullover', 'Dumbbell Chest Pullover'],
    category: 'dumbbell',
    primaryMuscles: ['lats', 'chest'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Lie perpendicular across a bench with shoulders on the pad. Hold one dumbbell with both hands above your chest. With a slight elbow bend, lower the dumbbell in an arc behind your head until you feel a stretch, then pull back to the start.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_db_shrug',
    name: 'Dumbbell Shrug',
    aliases: ['DB Shrug'],
    category: 'dumbbell',
    primaryMuscles: ['traps'],
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand holding dumbbells at your sides. Shrug your shoulders straight up as high as possible, hold briefly at the top, then lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_wrist_curl',
    name: 'Dumbbell Wrist Curl',
    aliases: ['DB Wrist Curl'],
    category: 'dumbbell',
    primaryMuscles: ['forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'bench'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Sit on a bench and rest your forearm on your thigh with your wrist hanging off the end, palm up. Let the dumbbell roll to your fingertips, then curl your wrist upward as high as possible. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_calf_raise',
    name: 'Dumbbell Calf Raise',
    aliases: ['DB Calf Raise', 'Standing Dumbbell Calf Raise'],
    category: 'dumbbell',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Hold a dumbbell in one hand for balance and stand on the edge of a step or on the floor. Rise up onto the balls of your feet as high as possible. Lower your heel below the step for a full stretch, then repeat.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_db_sumo_squat',
    name: 'Dumbbell Sumo Squat',
    aliases: ['DB Sumo Squat', 'Wide Stance DB Squat'],
    category: 'dumbbell',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'adductors'],
    equipment: ['dumbbell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with feet wider than shoulder-width and toes flared 45 degrees. Hold a dumbbell vertically with both hands between your legs. Squat down, keeping your chest up and knees tracking over your toes, then drive back up.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },

  // ─── MACHINE (15) ─────────────────────────────────────────────────────────────

  {
    id: 'ex_machine_leg_press',
    name: 'Leg Press',
    aliases: ['Machine Leg Press', '45 Degree Leg Press'],
    category: 'machine',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['machine'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit in the leg press machine and place your feet shoulder-width apart on the platform. Release the safety handles, lower the platform until your knees reach 90 degrees, then press back to near-lockout. Do not lock out your knees fully.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_machine_leg_extension',
    name: 'Leg Extension',
    aliases: ['Machine Leg Extension', 'Quad Extension'],
    category: 'machine',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Sit in the leg extension machine with the pad resting on your lower shins. Extend both legs to near full lockout, squeezing your quads at the top. Lower under control to the starting position.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_machine_seated_leg_curl',
    name: 'Seated Leg Curl',
    aliases: ['Seated Hamstring Curl'],
    category: 'machine',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Sit in the machine with the pad on top of your lower quads and the roller behind your heels. Curl your legs down as far as possible, squeezing your hamstrings, then return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_machine_lying_leg_curl',
    name: 'Lying Leg Curl',
    aliases: ['Prone Leg Curl', 'Machine Lying Leg Curl'],
    category: 'machine',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
    equipment: ['machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Lie face down on the machine with the roller just above your heels. Curl your legs up as far as possible, squeezing your hamstrings at the top. Lower under control without letting the weights touch.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_machine_chest_press',
    name: 'Chest Press Machine',
    aliases: ['Machine Chest Press', 'Plate-Loaded Chest Press'],
    category: 'machine',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delt'],
    equipment: ['machine'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit in the chest press machine with the handles at chest height. Press the handles forward until your arms are extended, then return under control to the starting position.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_machine_shoulder_press',
    name: 'Shoulder Press Machine',
    aliases: ['Machine Shoulder Press', 'Seated Press Machine'],
    category: 'machine',
    primaryMuscles: ['shoulders', 'front_delt'],
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit in the shoulder press machine and grip the handles at shoulder height. Press overhead to near lockout, then lower under control. Adjust the seat height so the handles start at shoulder level.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_cable_lat_pulldown',
    name: 'Cable Lat Pulldown',
    aliases: ['Lat Pulldown', 'Cable Pulldown'],
    category: 'machine',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'rear_delt'],
    equipment: ['cable', 'machine'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit at the cable machine and grip the bar wider than shoulder-width. Pull the bar down to your upper chest, driving your elbows down and back. Lean back slightly and squeeze your lats at the bottom. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_cable_seated_row',
    name: 'Seated Cable Row',
    aliases: ['Cable Row', 'Low Cable Row'],
    category: 'machine',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['cable', 'machine'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Sit at the cable row machine with feet on the platform and a slight knee bend. Pull the handle to your lower sternum while maintaining an upright torso. Squeeze your shoulder blades together at the end. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_machine_chest_fly',
    name: 'Chest Fly Machine',
    aliases: ['Pec Deck', 'Machine Fly', 'Pec Deck Fly'],
    category: 'machine',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Sit in the pec deck with your back flat against the pad. Place your forearms or hands on the padded arm rests. Bring your arms together in an arc, squeezing your chest at the peak contraction. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_cable_face_pull',
    name: 'Cable Face Pull',
    aliases: ['Face Pull', 'Rope Face Pull'],
    category: 'machine',
    primaryMuscles: ['rear_delt', 'upper_back'],
    secondaryMuscles: ['traps', 'biceps'],
    equipment: ['cable', 'machine'],
    movementPattern: 'pull_horizontal',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Attach a rope to a high cable pulley. Grip both ends of the rope and pull it toward your face, separating your hands as you pull. Your upper arms should finish parallel to the floor and hands by your ears. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_curl_machine',
    name: 'Cable Curl',
    aliases: ['Machine Cable Curl'],
    category: 'machine',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable', 'machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand at a low cable pulley with a straight bar or EZ attachment. Keeping your elbows at your sides, curl the bar to your upper chest. Squeeze at the top, then lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_tricep_pushdown',
    name: 'Tricep Pushdown',
    aliases: ['Cable Tricep Pushdown', 'Rope Pushdown', 'Cable Pushdown'],
    category: 'machine',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable', 'machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand at a high cable pulley with a rope or bar attachment. With elbows pinned to your sides, push the attachment down until your arms are fully extended. Contract your triceps and return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_machine_leg_press_calf_raise',
    name: 'Leg Press Calf Raise',
    aliases: ['Machine Calf Press', 'Calf Press on Leg Press'],
    category: 'machine',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set up in the leg press machine with only the balls of your feet on the bottom edge of the platform. Extend and flex your ankles to raise and lower the platform. Keep your legs straight or very slightly bent throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_smith_machine_squat',
    name: 'Smith Machine Squat',
    aliases: ['Smith Squat'],
    category: 'machine',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower_back'],
    equipment: ['smith_machine'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Position the bar on your upper traps in the Smith machine. Place feet slightly forward of the bar. Unlock the bar, squat to parallel or below, then drive back up. Lock the bar at the top between sets.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_machine_hack_squat',
    name: 'Hack Squat Machine',
    aliases: ['Machine Hack Squat', 'Plate-Loaded Hack Squat'],
    category: 'machine',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['machine'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Step into the hack squat machine, placing shoulders under the pads and feet shoulder-width on the platform. Release the safety, lower until thighs are parallel or below, then drive back up. Keep your lower back pressed to the pad throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },

  // ─── CABLE (15) ───────────────────────────────────────────────────────────────

  {
    id: 'ex_cable_crossover',
    name: 'Cable Crossover',
    aliases: ['Cable Cross', 'Standing Cable Fly'],
    category: 'cable',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set both cables to a high position. Stand in the center, step forward, and bring both handles down and together in front of your hips in a hugging motion. Squeeze your chest at the point of peak contraction. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_high_fly',
    name: 'High Cable Fly',
    aliases: ['High-to-Low Cable Fly', 'Cable Pec Fly High'],
    category: 'cable',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set cables high. Stand in the middle, grab one handle in each hand, and pull them down and together to hip height in a wide arc. Focus on the lower chest. Return with control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_low_fly',
    name: 'Low Cable Fly',
    aliases: ['Low-to-High Cable Fly', 'Cable Pec Fly Low'],
    category: 'cable',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front_delt'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set cables low at ankle height. Stand in the center, grab handles, and pull them up and together in an arc to chest height. Focus on the upper chest. Return with control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_lateral_raise',
    name: 'Cable Lateral Raise',
    aliases: ['Cable Side Raise'],
    category: 'cable',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['traps'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Set a low cable to ankle height. Stand sideways and grab the handle with the far hand. Raise your arm out to the side until parallel to the floor. Lower under control. Keep constant tension on the delt.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_rear_delt_fly',
    name: 'Cable Rear Delt Fly',
    aliases: ['Cable Reverse Fly', 'Cable Rear Delt Raise'],
    category: 'cable',
    primaryMuscles: ['rear_delt'],
    secondaryMuscles: ['upper_back'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set cables to shoulder height. Stand between them and cross your hands to grab the opposite handles. Pull both handles out to your sides in a reverse fly motion, squeezing your rear delts. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    aliases: ['Cable Pullover', 'Straight Arm Cable Pushdown'],
    category: 'cable',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['triceps', 'abs'],
    equipment: ['cable'],
    movementPattern: 'pull_vertical',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set a high cable with a bar or rope. Stand back and hinge forward slightly. Keeping your arms straight, pull the attachment down in an arc to your thighs. Squeeze your lats at the bottom. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_row',
    name: 'Cable Row',
    aliases: ['Standing Cable Row', 'Bent-Over Cable Row'],
    category: 'cable',
    primaryMuscles: ['upper_back', 'lats'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['cable'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand or hinge slightly at a low cable with a bar or handle. Pull the cable to your lower chest while driving your elbows back. Squeeze your shoulder blades at the end. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_cable_curl',
    name: 'Cable Curl',
    aliases: ['Standing Cable Curl'],
    category: 'cable',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Stand at a low cable with a bar or EZ attachment. Keeping elbows at your sides, curl the bar to your upper chest. Squeeze at the top, then lower under control. The cable provides constant tension throughout the range.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_overhead_tricep_extension',
    name: 'Overhead Cable Tricep Extension',
    aliases: ['Cable Overhead Extension', 'Cable French Press'],
    category: 'cable',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Set a high cable with a rope attachment. Face away from the machine and hold the rope overhead. Keeping your upper arms vertical beside your head, extend your elbows until your arms are straight. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_kickback',
    name: 'Cable Kickback',
    aliases: ['Cable Tricep Kickback'],
    category: 'cable',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Set a low cable. Hinge forward and keep your upper arm parallel to the floor. Extend your elbow until your arm is straight, squeezing your tricep at the top. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_hip_abduction',
    name: 'Cable Hip Abduction',
    aliases: ['Standing Cable Hip Abduction', 'Cable Glute Abduction'],
    category: 'cable',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Attach a cuff to a low cable and your outside ankle. Stand sideways to the machine and raise your leg out to the side as high as possible, keeping it straight. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_hip_adduction',
    name: 'Cable Hip Adduction',
    aliases: ['Standing Cable Hip Adduction', 'Cable Inner Thigh'],
    category: 'cable',
    primaryMuscles: ['glutes'],
    secondaryMuscles: [],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Attach a cuff to a low cable and your outside ankle. Stand perpendicular to the machine, lift the cuffed leg across your body, squeezing your inner thigh. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_woodchop',
    name: 'Cable Woodchop',
    aliases: ['Rotational Cable Pull', 'Cable Twist'],
    category: 'cable',
    primaryMuscles: ['obliques', 'abs'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    movementPattern: 'rotation',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Set a high cable and stand sideways. Grip the handle with both hands and pull it diagonally across your body from high to low, rotating your torso. Control the return. Keep arms relatively straight.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_pallof_press',
    name: 'Pallof Press',
    aliases: ['Cable Pallof Press', 'Anti-Rotation Press'],
    category: 'cable',
    primaryMuscles: ['abs', 'obliques'],
    secondaryMuscles: ['shoulders'],
    equipment: ['cable'],
    movementPattern: 'rotation',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Set a cable to chest height and stand perpendicular to it. Hold the handle with both hands at your chest. Press the handle straight out in front of you and hold briefly, resisting rotation. Return the handle to your chest.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_cable_crunch',
    name: 'Cable Crunch',
    aliases: ['Kneeling Cable Crunch', 'Rope Crunch'],
    category: 'cable',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques'],
    equipment: ['cable'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Kneel in front of a high cable with a rope attachment behind your head. Keeping your hips locked in place, crunch your elbows toward your knees, rounding your lower back. Squeeze your abs at the bottom. Return under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },

  // ─── BODYWEIGHT (15) ──────────────────────────────────────────────────────────

  {
    id: 'ex_bw_pull_up',
    name: 'Pull-Up',
    aliases: ['Standard Pull-Up', 'Overhand Pull-Up'],
    category: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'upper_back', 'rear_delt'],
    equipment: ['pull_up_bar'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hang from a pull-up bar with a pronated (overhand) grip wider than shoulder-width. Pull your chin above the bar by driving your elbows down and back. Lower under control to full arm extension.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_bw_chin_up',
    name: 'Chin-Up',
    aliases: ['Supinated Pull-Up', 'Underhand Pull-Up'],
    category: 'bodyweight',
    primaryMuscles: ['lats', 'biceps'],
    secondaryMuscles: ['upper_back', 'rear_delt'],
    equipment: ['pull_up_bar'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hang from a pull-up bar with a supinated (underhand) grip at shoulder-width. Pull your chin above the bar. Lower under control to full arm extension. The underhand grip increases bicep engagement.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_bw_wide_grip_pull_up',
    name: 'Wide-Grip Pull-Up',
    aliases: ['Wide Pull-Up'],
    category: 'bodyweight',
    primaryMuscles: ['lats'],
    secondaryMuscles: ['upper_back', 'rear_delt'],
    equipment: ['pull_up_bar'],
    movementPattern: 'pull_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hang from a pull-up bar with a very wide overhand grip. Pull your upper chest to the bar, leading with your elbows out to the sides. Lower under control. The wider grip maximises lat stretch.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_bw_push_up',
    name: 'Push-Up',
    aliases: ['Press-Up', 'Standard Push-Up'],
    category: 'bodyweight',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'front_delt', 'abs'],
    equipment: ['bodyweight'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Start in a high plank with hands slightly wider than shoulder-width. Lower your chest to the floor, keeping your body rigid and elbows at 45 degrees. Press back up to the start position.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_diamond_push_up',
    name: 'Diamond Push-Up',
    aliases: ['Triangle Push-Up', 'Close-Grip Push-Up'],
    category: 'bodyweight',
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['chest', 'front_delt'],
    equipment: ['bodyweight'],
    movementPattern: 'push_horizontal',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Form a diamond shape with your thumbs and index fingers on the floor beneath your chest. Keeping your elbows close to your body, lower your chest to your hands, then press back up.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_dip',
    name: 'Dip',
    aliases: ['Parallel Bar Dip', 'Bodyweight Dip'],
    category: 'bodyweight',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['front_delt', 'shoulders'],
    equipment: ['dip_bar'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Support your body on parallel bars with arms extended. Lower yourself by bending your elbows until your upper arms are parallel to the floor. Press back up to lockout. Lean forward for more chest activation; stay upright for more tricep activation.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_bw_ring_dip',
    name: 'Ring Dip',
    aliases: ['Gymnastic Ring Dip'],
    category: 'bodyweight',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: ['front_delt', 'abs'],
    equipment: ['bodyweight'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Support yourself on rings with arms extended and rings turned out. Lower yourself until your shoulders are below your elbows, keeping rings close to your body. Press back up and turn the rings out at the top. Keep your core tight throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_bw_hanging_leg_raise',
    name: 'Hanging Leg Raise',
    aliases: ['Hanging Knee Raise', 'Dead Hang Leg Raise'],
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'hip_flexors'],
    equipment: ['pull_up_bar'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Hang from a pull-up bar with arms fully extended. Keeping your legs straight (or bent for a regression), raise them to hip height or above. Lower under control without swinging. Avoid using momentum.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    aliases: ['Ab Roller', 'Ab Wheel'],
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['lats', 'triceps', 'lower_back'],
    equipment: ['bodyweight'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Kneel on the floor holding an ab wheel. Roll forward as far as you can while keeping your core braced and hips extended, preventing your lower back from arching. Roll back by contracting your abs. Start with partial range of motion.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_plank',
    name: 'Plank',
    aliases: ['Front Plank', 'Prone Plank'],
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['obliques', 'lower_back', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: false,
    instructions:
      'Start in a forearm plank with elbows under shoulders. Keep your body in a straight line from head to heels. Brace your core and squeeze your glutes. Hold for the prescribed time without letting your hips sag or rise.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_side_plank',
    name: 'Side Plank',
    aliases: ['Lateral Plank'],
    category: 'bodyweight',
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['abs', 'glutes', 'shoulders'],
    equipment: ['bodyweight'],
    movementPattern: 'isolation',
    isCompound: false,
    isUnilateral: true,
    instructions:
      'Lie on your side and prop yourself on your forearm, keeping your elbow under your shoulder. Lift your hips to form a straight line from head to feet. Hold for the prescribed time. Repeat on the other side.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 60,
  },
  {
    id: 'ex_bw_l_sit',
    name: 'L-Sit',
    aliases: ['L Sit Hold'],
    category: 'bodyweight',
    primaryMuscles: ['abs'],
    secondaryMuscles: ['triceps', 'quads', 'shoulders'],
    equipment: ['bodyweight', 'dip_bar'],
    movementPattern: 'isolation',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Support your body on parallettes, dip bars, or the floor with arms straight. Lift your legs parallel to the floor, forming an L shape with your body. Hold as long as possible while maintaining straight legs and arms.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_bw_pistol_squat',
    name: 'Pistol Squat',
    aliases: ['Single-Leg Squat', 'One-Leg Squat'],
    category: 'bodyweight',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'calves'],
    equipment: ['bodyweight'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Stand on one leg with the other extended forward. Descend by sitting back and down on the single leg, keeping the extended leg off the floor. Reach full depth with your glute touching your calf, then press back up to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_bw_box_jump',
    name: 'Box Jump',
    aliases: ['Jump Box', 'Plyometric Box Jump'],
    category: 'bodyweight',
    primaryMuscles: ['glutes', 'quads'],
    secondaryMuscles: ['hamstrings', 'calves', 'abs'],
    equipment: ['bodyweight'],
    movementPattern: 'cardio',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand in front of a sturdy box. Drop into a quarter squat and jump explosively, landing softly on the box with both feet in a quarter squat position. Stand to full extension, then step (not jump) back down.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_bw_burpee',
    name: 'Burpee',
    aliases: ['Squat Thrust'],
    category: 'bodyweight',
    primaryMuscles: ['quads', 'glutes', 'chest'],
    secondaryMuscles: ['abs', 'triceps', 'shoulders', 'hamstrings'],
    equipment: ['bodyweight'],
    movementPattern: 'cardio',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand upright, then drop your hands to the floor and jump your feet back to a plank. Perform a push-up, jump your feet back to your hands, then explode up with a jump, reaching arms overhead. Land softly and repeat.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },

  // ─── KETTLEBELL (10) ──────────────────────────────────────────────────────────

  {
    id: 'ex_kb_swing',
    name: 'Kettlebell Swing',
    aliases: ['KB Swing', 'Russian Swing', 'American Swing'],
    category: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['lower_back', 'abs', 'shoulders'],
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with feet shoulder-width apart. Hike the kettlebell back between your legs, then drive your hips forward explosively to swing the bell to shoulder height. Allow the bell to swing back and hinge your hips to absorb the load. Maintain a flat back throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_goblet_squat',
    name: 'Kettlebell Goblet Squat',
    aliases: ['KB Goblet Squat'],
    category: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'abs', 'upper_back'],
    equipment: ['kettlebell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Hold the kettlebell by the horns at chest height. Stand with feet shoulder-width apart. Squat down, keeping your chest up and elbows inside your knees at the bottom. Drive back up through your heels.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_clean',
    name: 'Kettlebell Clean',
    aliases: ['KB Clean'],
    category: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings', 'upper_back'],
    secondaryMuscles: ['traps', 'forearms', 'abs'],
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Start in a hip hinge with the kettlebell between your feet. Hike the bell back, then drive your hips forward and pull the bell up close to your body, rotating your hand to catch it in the rack position (bell resting on forearm at shoulder level). Reverse to the swing and repeat.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_press',
    name: 'Kettlebell Press',
    aliases: ['KB Press', 'KB Overhead Press', 'KB Military Press'],
    category: 'kettlebell',
    primaryMuscles: ['shoulders', 'front_delt'],
    secondaryMuscles: ['triceps', 'abs', 'traps'],
    equipment: ['kettlebell'],
    movementPattern: 'push_vertical',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Hold the kettlebell in rack position at shoulder. Brace your core and press the bell overhead to full lockout, packing your shoulder at the top. Lower under control back to rack position.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_snatch',
    name: 'Kettlebell Snatch',
    aliases: ['KB Snatch'],
    category: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings', 'shoulders'],
    secondaryMuscles: ['traps', 'upper_back', 'triceps'],
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Swing the kettlebell back and drive your hips forward. As the bell rises, punch your hand through and overhead in one smooth motion, catching it in an overhead lockout. Lower to the swing position and repeat. Keep the bell close to your body throughout.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_deadlift',
    name: 'Kettlebell Deadlift',
    aliases: ['KB Deadlift'],
    category: 'kettlebell',
    primaryMuscles: ['glutes', 'hamstrings', 'lower_back'],
    secondaryMuscles: ['quads', 'traps', 'forearms'],
    equipment: ['kettlebell'],
    movementPattern: 'hinge',
    isCompound: true,
    isUnilateral: false,
    instructions:
      'Stand with the kettlebell between your feet. Hinge at the hips, grasp the handle, and brace your core. Drive your feet into the floor to stand up fully with the bell. Hinge back down to return it to the floor.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_row',
    name: 'Kettlebell Row',
    aliases: ['KB Row', 'Single Arm KB Row'],
    category: 'kettlebell',
    primaryMuscles: ['lats', 'upper_back'],
    secondaryMuscles: ['biceps', 'rear_delt'],
    equipment: ['kettlebell'],
    movementPattern: 'pull_horizontal',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Place one hand on a bench for support. Hinge forward and let the kettlebell hang from the opposite arm. Pull the kettlebell to your hip by driving your elbow back. Lower under control.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_lunge',
    name: 'Kettlebell Lunge',
    aliases: ['KB Lunge', 'KB Reverse Lunge'],
    category: 'kettlebell',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
    equipment: ['kettlebell'],
    movementPattern: 'squat',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Hold a kettlebell in each hand or in rack position. Step forward and lower your back knee toward the floor, keeping your front shin vertical. Drive through your front heel to return. Alternate legs or complete all reps on one side.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
  {
    id: 'ex_kb_turkish_get_up',
    name: 'Kettlebell Turkish Get-Up',
    aliases: ['TGU', 'Turkish Get-Up'],
    category: 'kettlebell',
    primaryMuscles: ['shoulders', 'abs'],
    secondaryMuscles: ['glutes', 'triceps', 'upper_back', 'quads'],
    equipment: ['kettlebell'],
    movementPattern: 'carry',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Lie on your back and press the kettlebell straight up with one arm. Using a series of controlled movements — roll to elbow, press to hand, bridge hips, sweep leg through, stand — rise to a full standing position while keeping the bell locked overhead. Reverse the movement to return to the floor.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 120,
  },
  {
    id: 'ex_kb_windmill',
    name: 'Kettlebell Windmill',
    aliases: ['KB Windmill'],
    category: 'kettlebell',
    primaryMuscles: ['obliques', 'shoulders'],
    secondaryMuscles: ['hamstrings', 'glutes', 'abs', 'lower_back'],
    equipment: ['kettlebell'],
    movementPattern: 'rotation',
    isCompound: true,
    isUnilateral: true,
    instructions:
      'Press a kettlebell overhead in one hand and rotate your feet 45 degrees away from that arm. Keeping the bell locked overhead and your eyes on it, hinge at the hip and lean toward the floor, sliding your free hand down your leg. Return to standing.',
    isCustom: false,
    isArchived: false,
    defaultRestSeconds: 90,
  },
] as const;
